### ISSUE TITLE
State of variables is not preserved after HA restart anymore

### ISSUE THREAD

**Issue by OleksandrBerchenko** [rogro82/hass-variables#11]
After upgrading HA to 0.84.2 (and applying the latest hass-variables fix), variables with `"restore": true` don't preserve their state after HA restart anymore.

**Comment by michbaeck** [comment]
Same here.

**Comment by rafuz** [comment]
I can confirm, same issue

**Comment by jghaanstra** [comment]
@rogro82 any plans on fixing this? It messes up my automation and data every time I reboot or upgrade. Or should I look for a different solution (which I dont want to because this always worked perfect for me).

**Comment by OleksandrBerchenko** [comment]
The fix works, thank you!
