### ISSUE TITLE
variable component doesn't work with HA 0.86.3

### ISSUE THREAD

**Issue by Hirgo** [rogro82/hass-variables#16]
Hello,

I upgraded my HA from 0.74.2 to 0.84.3. Unfortunately the variable custom component doesn't work anymore, it's not loaded at all. I don't see it as a loaded component in the list.

I tried multiple variable file versions (the old one I used with HA 0.74.2, rogro82's one from 13th Dec and the newest one from 28th Dec) but it doesn't work, too.

Surprisingly there's no message in the log related to this component. Also nothing like "couldn't load component...".

I thought it's something related to my configuration.yaml. If I want to check the configuration.yaml in the "settings" menu, the check never ends and shows no result as long as I have the "variable.py" file stored in the "custom_components" folder. If I remove the variable.py file, the "configuration.yaml" check is done successfully.

Do I do something wrong? I worked with my HA 0.74.2 very well in the past. I didn't change anything except upgrading HA to 0.86.3.

Best regards,
Hirgo

**Comment by OleksandrBerchenko** [comment]
That's strange: I have recently upgraded to 0.86.4, and it still works fine.  I use the latest version from this github repo.

Thanks!

**Comment by Hirgo** [comment]
I'm very sorry, it was my fault. During the upgrade anything crashed the variable.py file on my Raspberry. 

And finally I didn't download the variable.py file correctly from Github.

Now it works fine with my HA 0.86.3, no issues.
