### ISSUE TITLE
Feature Request: variable_template

### ISSUE THREAD

**Issue by lenwar** [rogro82/hass-variables#39]
Is it possible to also use variables as templates.
The purpose would to be to be able to create generic scripts that work for multiple variables. (so without having to create the same script for each variables)
My current workaround is to have one variable with loads of attributes. But it looks cleaner to have them seperated.

**Comment by gribouk** [comment]
As far as I know, everything, that has 'data' supports templating for the inner field after replacement of 'data' with 'data_template'. So, technically, the value_template and attributes_template are excessive, and you can template 'variable' field right away...
