### ISSUE TITLE
HACS install creates var directory rather than variable in custom_components

### ISSUE THREAD

**Issue by marclefevre** [rogro82/hass-variables#41]
I just installed the integration using HACS and was getting error messages about integration 'variable' not found.  I looked in custom_components and found that the directory was named 'var' (the old name, right?).  After renaming var to variable, the error messages went away.

**Comment by snarky-snark** [comment]
The integration in HACS is [this integration](https://github.com/snarky-snark/home-assistant-variables).

**Comment by marclefevre** [comment]
I could not find the Variable integration in HACS.  I did clear my browser
cache with no change.

So, I took the route of installing from the zip file.  My original post
came from confusion about the name of the integration (variable) and the
name of the component (var).  I'm still having problems getting it to work.

I deleted ./custom_components/var and re-unzipped the original zip file
there.  Restarting HA results in the following error:

'''
Setup failed for var: Unable to import component: cannot import name
'ENTITY_SERVICE_SCHEMA' from 'homeassistant.helpers.config_validation'
(/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py)

'''
There must be something simple I'm forgetting.  I had this working on an
old server running HA  0.101.3.

Marc

**Comment by snarky-snark** [comment]
It sounds like you might be installing an older release.

Just a reminder, you created this issue in the hass-variables repo which has no relation to the integration you seem to be trying to install which is located at this repo:

https://github.com/snarky-snark/home-assistant-variables

**Comment by marclefevre** [comment]
You are right.  Should I start a new issue or continue here?

I have been working on this all day by uninstalling and reinstalling and
googling the issues.  I finally got it to show up HACS and I have rebooted
to finish the configuration but I still get

'''
Setup failed for var: Integration failed to initialize.
'''

and nothing else to go on.  Are there other logs I can look at?  Can I bump
the verbosity higher?  What I have in configuration.yaml is

'''
logger:
  default: info
  logs:
    homeassistant.core: info
    homeassistant.components.mqtt: info
'''

Thanks for your help.

Marc

**Comment by snarky-snark** [comment]
It would be best to create a new issue in the home-assistant-variables repo since this repo is unrelated to the integration you are trying to install.

What version of the variable integration are you trying to install? What version of HACS? It sounds like the issue might be with HACS and not this component.

You might try adding config for a variable to see if that changes things. For example,
```
var:
  x:
    initial_value: 0
```

**Comment by marclefevre** [comment]
Starting a new issue in the correct repo.
