### ISSUE TITLE
hass-variables NOT working after 2021.6.0 update

### ISSUE THREAD

**Issue by pickonedev** [rogro82/hass-variables#58]
Hi!

Any solution in order to use this integration with home assistant 2021.6.0 new update?

**Comment by skynet01** [comment]
Oh boy same thing here, broke half my stuff. Any updates on the fix @rogro82 ? I assume it's something small?

**Comment by phr0z** [comment]
Wibias fork seems to be working with 2021.6.0. It's on HACS as well and it appears to be maintained.

**Comment by YvesZH** [comment]
same here - It's not working after update 2021.6.0

_2021-06-03 09:50:37 ERROR (MainThread) [homeassistant.setup] Setup failed for variable: Integration not found._

**Comment by Mariusthvdb** [comment]
simply add the (a) version key to your manifest.json which is now required for all custom integrations:
```
    "version": "1.2",
```
and you're set

**Comment by nytram-md** [comment]
I can confirm adding the version above works. I did however have to remove the addon first for a reboot and then re-install the variable HACS addon and add the version to the file and it worked.

My Home Assistant would not reboot at first as it said the Variable HACS addon was not available.

Thanks 

Martyn

**Comment by Mariusthvdb** [comment]
ok, glad you sorted it. maybe close this issue then, as the one listed below thisnissue in the issue list has a title covering the issue more precisely.

**Comment by Wibias** [comment]
> 
> 
> Wibias fork seems to be working with 2021.6.0. It's on HACS as well and it appears to be maintained.

Yea my forked is updated completly with some added functions. Also the unecessary stuff got removed. Feel Free to use it. It's not on Hacs yet, since its still waiting for approval.

https://github.com/Wibias/hass-variables

https://github.com/hacs/default/pull/965

**Comment by YvesZH** [comment]
> Yea my forked is updated completly with some added functions. 
@Wibias Perfect - thank you!
Without having read all the details: Can I replace your file and I don't have to change anything in the configuration.yaml? Or are there differences, so I should read through the documentation and make yaml adjustments. Sorry for my lazy question

**Comment by Wibias** [comment]
I mean if you have changed it the last time it gave some errors(There was an update a while ago concerning templates) you shouldn't have to change anything. If you are not sure just look at my Readme as there are updated Examples.

**Comment by pickonedev** [comment]
Dear @Wibias , There are some problems with your addon... There is any way in solving this?
Let me explain first:

When I saw yesterday that the old variable addon it is not working anymore with the new home assistant version, I found this alternative (your addon, which you updated and stuff), all good, I was very happy, then... checking the logs, I saw that there are some errors with some automations which I have, where I used variables with templates as values, as you can see in the next part of the automation
`choose:
  - conditions:
      - condition: template
        value_template: >-
          {% if trigger.entity_id == 'sensor.broadlink_bedroom_humidity' or
          trigger.entity_id == 'variable.bedroom_temphum_humidity' %} true {%
          endif %}
    sequence:
      - service: variable.set_variable
        data:
          variable: bedroom_humidity
          value_template: >-
            {% if (((states("sensor.broadlink_bedroom_humidity") | float) +
            (states("variable.bedroom_temphum_humidity") | float)) / 2) <= 35 %}
            low {% elif (((states("sensor.broadlink_bedroom_humidity") | float)
            + (states("variable.bedroom_temphum_humidity") | float)) / 2) >= 65
            %} high {% else %} normal {% endif %}
default: []`

Seeing these errors in the log (I am sorry that I did not made a screenshot to show it here...), something  about variables attribute templates... I don't remember exactly, I started the find other alternative, then I remebered that the old addon could work again if I add the "version" line into the manifest, which I did, then I checked if there are any errors in the log, with the old addon, and there is no error in the log.
Comparing the __init__.py files of both addons, I've seen that there are some lines missing in your addon, some lines about value template...
There is any way to modify you addon in order to avoid those errors?

Thank you in advance!

**Comment by Wibias** [comment]
@pickonedev

Yea just change value_template: to value:

That should do it.

**Comment by pickonedev** [comment]
Oh, ok, I understand... So, every line which I used as "value_template", I only need to use "value" and it will use templates too. Nice! I will try asap. Thank you!

**Comment by pickonedev** [comment]
Good! Seems that it is now working. My bad that I did not check  the samples from your addon, I didn't know that there are any differences between usability, but this is even better.

Thank you so much!
